"""Plot the scaled area-loss heatmaps from the scaled-area-loss workflow.

The border CSVs are generated by the ``feature/scaled-area-loss`` branch's
``plotRS.py``.  This script keeps the plotting step independent so it can be
rerun without solving the model again.
"""

from __future__ import annotations

import csv
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import colors
from matplotlib.collections import LineCollection
from matplotlib.ticker import PercentFormatter
from shapely.geometry import Polygon


DATA_DIR = Path(os.environ.get("NCC_AREA_LOSS_DATA_DIR", "plots_data"))
OUTPUT_DIR = Path(os.environ.get("NCC_AREA_LOSS_OUTPUT_DIR", "plots_png")) / "compensation_mu_max_and_mu_incr"
BASELINE_MU_MAX = 1.2
BASELINE_MU_INCR = 1.1
MU_MAX_VALUES = [round(value, 1) for value in np.arange(1.2, 2.01, 0.1)]
MU_INCR_VALUES = [round(value, 1) for value in np.arange(1.1, 1.71, 0.1)]
TARGETS = [(17, 2100), (19, 2110), (21, 2120)]
T_DEVS = [4, 5, 6, 7, 8]
RECOVERY_THRESHOLD = 0.05


def border_path(mu_max: float, mu_incr: float, t_dev: int, target_t: int) -> Path:
    target_year = 2015 + 5 * int(target_t)
    return DATA_DIR / (
        f"NCC_mu{mu_max:.2f}_muincr{mu_incr:.2f}"
        f"_tdev{t_dev}_year{target_year}.csv"
    )


def load_points(path: Path) -> np.ndarray:
    points = np.loadtxt(path, delimiter=",")
    if points.ndim == 1:
        points = points.reshape(1, -1)
    if points.shape[1] != 2:
        raise ValueError(f"Expected two columns in {path}, got {points.shape[1]}.")
    return points


def polygon(points: np.ndarray, label: str) -> Polygon:
    result = Polygon(points)
    if not result.is_valid or result.is_empty:
        raise ValueError(f"Invalid border polygon for {label}: {result.is_valid}")
    return result


def scaled(points: np.ndarray, bounds: tuple[float, float, float, float]) -> np.ndarray:
    q_min, q_max, temp_min, temp_max = bounds
    result = np.empty_like(points, dtype=float)
    result[:, 0] = (points[:, 0] - q_min) / max(q_max - q_min, 1e-12)
    result[:, 1] = (points[:, 1] - temp_min) / max(temp_max - temp_min, 1e-12)
    return result


def loss_matrix(target_t: int, target_year: int, t_dev: int) -> np.ndarray:
    base_path = border_path(BASELINE_MU_MAX, BASELINE_MU_INCR, 1, target_t)
    base_raw = load_points(base_path)
    bounds = (
        float(base_raw[:, 0].min()),
        float(base_raw[:, 0].max()),
        float(base_raw[:, 1].min()),
        float(base_raw[:, 1].max()),
    )
    base = polygon(scaled(base_raw, bounds), f"baseline {target_year}")

    matrix = np.full((len(MU_INCR_VALUES), len(MU_MAX_VALUES)), np.nan)
    for row, mu_incr in enumerate(MU_INCR_VALUES):
        for col, mu_max in enumerate(MU_MAX_VALUES):
            path = border_path(mu_max, mu_incr, t_dev, target_t)
            comp = polygon(
                scaled(load_points(path), bounds),
                f"{path.name}",
            )
            matrix[row, col] = base.difference(comp).area / base.area
    return matrix


def cell_edges(values: list[float]) -> np.ndarray:
    """Return cell edges whose centers are the computed parameter values."""
    centers = np.asarray(values, dtype=float)
    if centers.ndim != 1 or centers.size < 2:
        raise ValueError("At least two one-dimensional grid values are required.")
    if not np.all(np.diff(centers) > 0):
        raise ValueError("Grid values must be strictly increasing.")

    edges = np.empty(centers.size + 1, dtype=float)
    edges[1:-1] = 0.5 * (centers[:-1] + centers[1:])
    edges[0] = centers[0] - 0.5 * (centers[1] - centers[0])
    edges[-1] = centers[-1] + 0.5 * (centers[-1] - centers[-2])
    return edges


def threshold_segments(
    matrix: np.ndarray,
    x_edges: np.ndarray,
    y_edges: np.ndarray,
    threshold: float,
) -> list[list[tuple[float, float]]]:
    """Trace a threshold only along boundaries between discrete grid cells."""
    retained = matrix <= threshold
    n_rows, n_cols = retained.shape
    segments: list[list[tuple[float, float]]] = []

    for row in range(n_rows):
        for boundary_col in range(1, n_cols):
            if retained[row, boundary_col - 1] != retained[row, boundary_col]:
                segments.append(
                    [
                        (x_edges[boundary_col], y_edges[row]),
                        (x_edges[boundary_col], y_edges[row + 1]),
                    ]
                )

    for boundary_row in range(1, n_rows):
        for col in range(n_cols):
            if retained[boundary_row - 1, col] != retained[boundary_row, col]:
                segments.append(
                    [
                        (x_edges[col], y_edges[boundary_row]),
                        (x_edges[col + 1], y_edges[boundary_row]),
                    ]
                )

    return segments


def plot_publication_heatmaps(
    matrices: dict[tuple[int, int], np.ndarray],
    vmax: float,
    output: Path,
) -> None:
    """Render Figure 4 without interpolating between computed grid cells."""
    expected_shape = (len(MU_INCR_VALUES), len(MU_MAX_VALUES))
    for key, matrix in matrices.items():
        if matrix.shape != expected_shape:
            raise ValueError(f"Matrix {key} has shape {matrix.shape}; expected {expected_shape}.")
        if not np.isfinite(matrix).all():
            raise ValueError(f"Matrix {key} contains a non-finite grid value.")

    x_edges = cell_edges(MU_MAX_VALUES)
    y_edges = cell_edges(MU_INCR_VALUES)
    norm = colors.Normalize(vmin=0.0, vmax=max(vmax, 1e-12))

    fig, axes = plt.subplots(
        len(T_DEVS),
        len(TARGETS),
        figsize=(8.2, 10.2),
        dpi=300,
        sharex=True,
        sharey=True,
        squeeze=False,
    )
    fig.subplots_adjust(
        left=0.23,
        right=0.86,
        bottom=0.11,
        top=0.91,
        wspace=0.08,
        hspace=0.10,
    )

    mesh = None
    for col, (target_t, target_year) in enumerate(TARGETS):
        for row, t_dev in enumerate(T_DEVS):
            ax = axes[row, col]
            matrix = matrices[(target_t, t_dev)]
            mesh = ax.pcolormesh(
                x_edges,
                y_edges,
                matrix,
                shading="flat",
                cmap="cividis_r",
                norm=norm,
                edgecolors="none",
                antialiased=False,
                rasterized=True,
            )

            segments = threshold_segments(
                matrix,
                x_edges,
                y_edges,
                RECOVERY_THRESHOLD,
            )
            if segments:
                ax.add_collection(
                    LineCollection(
                        segments,
                        colors="0.25",
                        linewidths=0.8,
                        zorder=3,
                    )
                )

            # Two outlines keep the benchmark visible on both light and dark cells.
            ax.scatter(
                [BASELINE_MU_MAX],
                [BASELINE_MU_INCR],
                s=32,
                facecolors="none",
                edgecolors="white",
                linewidths=2.2,
                zorder=5,
            )
            ax.scatter(
                [BASELINE_MU_MAX],
                [BASELINE_MU_INCR],
                s=32,
                facecolors="none",
                edgecolors="black",
                linewidths=0.75,
                zorder=6,
            )

            ax.set_xlim(x_edges[0], x_edges[-1])
            ax.set_ylim(y_edges[0], y_edges[-1])
            ax.set_xticks(MU_MAX_VALUES)
            ax.set_yticks(MU_INCR_VALUES)
            ax.tick_params(axis="both", labelsize=7, length=2.5, pad=2)
            ax.label_outer()

            if row == 0:
                ax.set_title(str(target_year), fontsize=10, pad=6)
    for ax in axes[-1, :]:
        plt.setp(
            ax.get_xticklabels(),
            rotation=45,
            ha="right",
            rotation_mode="anchor",
        )

    for row, t_dev in enumerate(T_DEVS):
        position = axes[row, 0].get_position()
        fig.text(
            0.075,
            0.5 * (position.y0 + position.y1),
            str(2015 + 5 * t_dev),
            ha="center",
            va="center",
            fontsize=9,
        )

    fig.text(0.545, 0.965, "Terminal year", ha="center", va="center", fontsize=11)
    fig.text(
        0.022,
        0.51,
        "Mitigation delayed until",
        ha="center",
        va="center",
        rotation=90,
        fontsize=11,
    )
    fig.text(
        0.545,
        0.025,
        r"Maximum admissible emission-reduction rate, $\mu_{\max}$",
        ha="center",
        va="center",
        fontsize=10,
    )
    fig.text(
        0.145,
        0.51,
        r"Maximum growth factor, $\mu_{\mathrm{incr}}$",
        ha="center",
        va="center",
        rotation=90,
        fontsize=10,
    )

    if mesh is not None:
        colorbar_ax = fig.add_axes([0.89, 0.18, 0.026, 0.65])
        colorbar = fig.colorbar(mesh, cax=colorbar_ax)
        colorbar.ax.yaxis.set_major_formatter(PercentFormatter(xmax=1.0, decimals=0))
        colorbar.ax.tick_params(labelsize=8, length=3)
        colorbar.set_label("Baseline opportunity space lost", fontsize=10, labelpad=9)

    fig.savefig(output, bbox_inches="tight", facecolor="white")
    plt.close(fig)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    matrices = {
        (target_t, t_dev): loss_matrix(target_t, target_year, t_dev)
        for target_t, target_year in TARGETS
        for t_dev in T_DEVS
    }
    vmax = max(float(np.nanmax(matrix)) for matrix in matrices.values())
    output = OUTPUT_DIR / "relative_uncovered_loss_heatmaps_3x5.png"
    plot_publication_heatmaps(matrices, vmax, output)

    table = OUTPUT_DIR / "relative_uncovered_loss_heatmaps_3x5.csv"
    with table.open("w", newline="") as handle:
        writer = csv.writer(handle)
        writer.writerow(["target_year", "delay_year", "mu_incr", *[f"mu_max={v:.1f}" for v in MU_MAX_VALUES]])
        for target_t, target_year in TARGETS:
            for t_dev in T_DEVS:
                matrix = matrices[(target_t, t_dev)]
                for row, mu_incr in enumerate(MU_INCR_VALUES):
                    writer.writerow([target_year, 2015 + 5 * t_dev, mu_incr, *matrix[row]])

    print(f"Saved: {output}")
    print(f"Saved: {table}")
    print(f"Relative uncovered-loss range: 0 .. {vmax:.6f}")


if __name__ == "__main__":
    main()
